/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ChuongTrinhUuDaiCon;
import Controller.DateCon;
import Controller.KhachHangCon;
import Model.ChuongTrinhUuDai;
import Model.ThongBao;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 16520
 */
public class frmQuanLyChuongTrinhUuDai extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmQuanLyChuongTrinhUuDai
     */
    public frmQuanLyChuongTrinhUuDai() {
        initComponents();
    }

    public void Show(){
        this.setVisible(true);
        LoadDanhSachCTUD();
        tfMaNV.setText(quanlytiemchuphinh.QuanLyTiemChupHinh.taiKhoanDangNhap.MANV);      
        XoaThongBao();
        OffAllBtns();
    }
    
    private void OffAllBtns(){
        btnThem.setEnabled(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
    }
    
    private void XoaThongBao(){
        lbThongBao.setText("");
    }
    
    private void ShowThongBao(ThongBao thongBao){
        lbThongBao.setText(thongBao.ChuThich);
        if (thongBao.ThanhCong){
           lbThongBao.setForeground(Color.GREEN);
        }
        else{
            lbThongBao.setForeground(Color.RED);
        }
    }
    
    public void  LoadDanhSachCTUD(){
        
        ArrayList<ChuongTrinhUuDai> listCTUD = ChuongTrinhUuDaiCon.LayDanhSachCTUD();
        ShowData(listCTUD);            
    }
    
    private void ShowData(ArrayList<ChuongTrinhUuDai> listCTUD){
        
        tableCTUD.clearSelection(); //Xoa du lieu table
        
        String header[] = {"Mã CTUD", "Mã NV", "Tên CTUD", "Ngày BD", "Ngày KT", "Nội dung", "GTUD"};
        DefaultTableModel tblModel = new DefaultTableModel(header, 0);
        
        tblModel.setRowCount(0);
        
        if (listCTUD != null) 
        {       
            // Trong khi chưa hết dữ liệu
           for (int i=0; i< listCTUD.size(); i++){
                Vector data = new Vector();           
                data.add(listCTUD.get(i).MACTUD);
                data.add(listCTUD.get(i).MANV);
                data.add(listCTUD.get(i).TENCTUD);
                data.add(listCTUD.get(i).NGAYBATDAU);
                data.add(listCTUD.get(i).NGAYKETTHUC);
                data.add(listCTUD.get(i).NOIDUNG);
                data.add(listCTUD.get(i).GIATRIUUDAI);
                // Thêm một dòng vào table model
                tblModel.addRow(data);
               }
        } 
        tableCTUD.setModel(tblModel); // Thêm dữ liệu vào table     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbDangApDung = new javax.swing.JCheckBox();
        dcTraCuuBD = new com.toedter.calendar.JDateChooser();
        dcTraCuuKT = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnTraCuu = new javax.swing.JButton();
        btnTraCuu1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCTUD = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfMaCTUD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfMaNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taNoiDung = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        tfGiaTriUuDai = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        dcNgayBatDau = new com.toedter.calendar.JDateChooser();
        dcNgayKetThuc = new com.toedter.calendar.JDateChooser();
        lbThongBao = new javax.swing.JLabel();
        tfTenCTUD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnThemMoi = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel8.setText("Tra cứu:");

        cbDangApDung.setText("Đang áp dụng");
        cbDangApDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDangApDungActionPerformed(evt);
            }
        });

        dcTraCuuBD.setDateFormatString("dd/MM/yyyy");

        dcTraCuuKT.setDateFormatString("dd/MM/yyyy");

        jLabel9.setText("Từ ngày");

        jLabel10.setText("Đến ngày");

        btnTraCuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES/iconfinder_Search_27877.png"))); // NOI18N
        btnTraCuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraCuuActionPerformed(evt);
            }
        });

        btnTraCuu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES/iconfinder_Escape_Search_27877.png"))); // NOI18N
        btnTraCuu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraCuu1ActionPerformed(evt);
            }
        });

        tableCTUD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCTUD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCTUDMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableCTUD);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(cbDangApDung))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(dcTraCuuBD, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(dcTraCuuKT, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTraCuu1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTraCuu, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTraCuu1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTraCuu))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcTraCuuBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbDangApDung)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(dcTraCuuKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setText("Mã chương trình ưu đãi:");

        tfMaCTUD.setEditable(false);
        tfMaCTUD.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Mã nhân viên:");

        tfMaNV.setEditable(false);
        tfMaNV.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("Ngày bắt đầu:");

        jLabel4.setText(" Ngày kết thúc:");

        jLabel5.setText("Nội dung:");

        taNoiDung.setColumns(20);
        taNoiDung.setRows(5);
        jScrollPane1.setViewportView(taNoiDung);

        jLabel6.setText("Giá trị ưu đãi");

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES/iconfinder_Delete_27842.png"))); // NOI18N
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES/iconfinder_Edit_27845.png"))); // NOI18N
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES/iconfinder_Check_27837.png"))); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        dcNgayBatDau.setDateFormatString("dd/MM/yyyy");

        dcNgayKetThuc.setDateFormatString("dd/MM/yyyy");

        lbThongBao.setText("Thông báo");

        jLabel7.setText("Tên CTUD:");

        btnThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES/iconfinder_Add_27831.png"))); // NOI18N
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfGiaTriUuDai, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfMaNV, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfMaCTUD, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfTenCTUD, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(btnThem)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSua)
                                    .addGap(27, 27, 27)
                                    .addComponent(btnXoa)
                                    .addGap(10, 10, 10))
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbThongBao, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(59, 59, 59)
                                    .addComponent(btnThemMoi))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dcNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(dcNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(tfMaCTUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTenCTUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfGiaTriUuDai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbThongBao)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableCTUDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCTUDMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)tableCTUD.getModel();

        // get the selected row index
       int selectedRowIndex = tableCTUD.getSelectedRow();
       
        // set the selected row data into jtextfields
       tfMaCTUD.setText(model.getValueAt(selectedRowIndex, 0).toString());
       tfMaNV.setText(model.getValueAt(selectedRowIndex, 1).toString());
       tfTenCTUD.setText(model.getValueAt(selectedRowIndex, 2).toString());
       dcNgayBatDau.setDate(DateCon.GetDate(model.getValueAt(selectedRowIndex, 3).toString()));
       dcNgayKetThuc.setDate(DateCon.GetDate(model.getValueAt(selectedRowIndex, 4).toString()));
       taNoiDung.setText(model.getValueAt(selectedRowIndex, 5).toString());
       tfGiaTriUuDai.setText(model.getValueAt(selectedRowIndex, 6).toString());
       
        SetEnableBtnThem(false);
    }//GEN-LAST:event_tableCTUDMouseClicked

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        // TODO add your handling code here:
        
        XoaDuLieuNhap();
        
        tfMaNV.setText(quanlytiemchuphinh.QuanLyTiemChupHinh.taiKhoanDangNhap.MANV);
        tfMaCTUD.setText(ChuongTrinhUuDaiCon.LayMaCTUDMoi());
        //Lay MaCTUD, MaNV
        SetEnableBtnThem(true);
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        ChuongTrinhUuDai ctud = new ChuongTrinhUuDai(
                tfMaCTUD.getText(), 
                tfMaNV.getText(),
                tfTenCTUD.getText(),
                DateCon.GetDateString(dcNgayBatDau),
                DateCon.GetDateString(dcNgayKetThuc),
                taNoiDung.getText(), 
                tfGiaTriUuDai.getText());
        ThongBao thongBao = ChuongTrinhUuDaiCon.ThemCTUD(ctud);
        LoadDanhSachCTUD();
        ShowThongBao(thongBao);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        ChuongTrinhUuDai ctud = new ChuongTrinhUuDai(
                tfMaCTUD.getText(), 
                tfMaNV.getText(),
                tfTenCTUD.getText(),
                DateCon.GetDateString(dcNgayBatDau),
                DateCon.GetDateString(dcNgayKetThuc),
                taNoiDung.getText(), 
                tfGiaTriUuDai.getText());
        ThongBao thongBao = ChuongTrinhUuDaiCon.SuaCTUD(ctud);
        LoadDanhSachCTUD();
        ShowThongBao(thongBao);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        ChuongTrinhUuDai ctud = new ChuongTrinhUuDai(
                tfMaCTUD.getText(), 
                tfMaNV.getText(),
                tfTenCTUD.getText(),
                DateCon.GetDateString(dcNgayBatDau),
                DateCon.GetDateString(dcNgayKetThuc),
                taNoiDung.getText(), 
                tfGiaTriUuDai.getText());
        ThongBao thongBao = ChuongTrinhUuDaiCon.XoaCTUD(ctud);
        LoadDanhSachCTUD();
        ShowThongBao(thongBao);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void cbDangApDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDangApDungActionPerformed
        // TODO add your handling code here:
        if (cbDangApDung.isSelected()){
            dcTraCuuBD.setDate(DateCon.GetToDay());
            dcTraCuuKT.setDate(DateCon.GetToDay());
            ArrayList<ChuongTrinhUuDai> listCTUDDangApDung = ChuongTrinhUuDaiCon.LayDanhSachCTUDTheoThoiGian(dcTraCuuBD.getDate(), dcTraCuuKT.getDate());
            ShowData(listCTUDDangApDung);
        }
        else {
            dcTraCuuBD.setDate(null);
            dcTraCuuKT.setDate(null);
            LoadDanhSachCTUD();
        }
        

    }//GEN-LAST:event_cbDangApDungActionPerformed

    private void btnTraCuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraCuuActionPerformed
        // TODO add your handling code here:
            cbDangApDung.setSelected(false);
            if (dcTraCuuBD.getDate()== null || dcTraCuuKT.getDate() == null) return;
            ArrayList<ChuongTrinhUuDai> listCTUDTheoNgay = ChuongTrinhUuDaiCon.LayDanhSachCTUDTheoThoiGian(dcTraCuuBD.getDate(), dcTraCuuKT.getDate());
            ShowData(listCTUDTheoNgay);
    }//GEN-LAST:event_btnTraCuuActionPerformed

    private void btnTraCuu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraCuu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTraCuu1ActionPerformed
    private void SetEnableBtnThem(Boolean isThem){
        btnThem.setEnabled(isThem);
        btnSua.setEnabled(!isThem);
        btnXoa.setEnabled(!isThem);
    }
    private void XoaDuLieuNhap(){
        tfMaCTUD.setText("");
        tfMaNV.setText("");
        tfTenCTUD.setText("");
        dcNgayBatDau.setDate(DateCon.GetToDay());
        dcNgayKetThuc.setDate(DateCon.GetToDay());
        taNoiDung.setText("");
        tfGiaTriUuDai.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnTraCuu;
    private javax.swing.JButton btnTraCuu1;
    private javax.swing.JButton btnXoa;
    private javax.swing.JCheckBox cbDangApDung;
    private com.toedter.calendar.JDateChooser dcNgayBatDau;
    private com.toedter.calendar.JDateChooser dcNgayKetThuc;
    private com.toedter.calendar.JDateChooser dcTraCuuBD;
    private com.toedter.calendar.JDateChooser dcTraCuuKT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbThongBao;
    private javax.swing.JTextArea taNoiDung;
    private javax.swing.JTable tableCTUD;
    private javax.swing.JTextField tfGiaTriUuDai;
    private javax.swing.JTextField tfMaCTUD;
    private javax.swing.JTextField tfMaNV;
    private javax.swing.JTextField tfTenCTUD;
    // End of variables declaration//GEN-END:variables
}
