/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BangHoachToanCon;
import Controller.ChiTietHoachToanCon;
import Controller.ChuongTrinhUuDaiCon;
import Controller.DateCon;
import Controller.PhieuChupCon;
import Model.BangHoachToan;
import Model.ChiTietHoachToan;
import Model.ChiTietPhieuChup;
import Model.ChuongTrinhUuDai;
import Model.PhieuChup;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import java.util.List;
/**
 *
 * @author 16520
 */
public class frmThanhToanPhieuChup extends javax.swing.JFrame {

    /**
     * Creates new form frmThanhToanPhieuChup
     */
    public frmThanhToanPhieuChup() {
        initComponents();
        LoadData();  //test
    }

    
    
    public void Show(PhieuChup phieuChup){
        this.setVisible(true);
        Form.Form.centreWindow(this);
        pc = phieuChup;
        LoadData();
    }
    
    PhieuChup pc = new PhieuChup();
    ChiTietPhieuChup ctpc = new ChiTietPhieuChup();
    ArrayList<ChuongTrinhUuDai> ctud;
    ArrayList<BangHoachToan> bht;
    ArrayList<ChiTietHoachToan> ctht;
    
    ChiTietHoachToan cthtSelected = new ChiTietHoachToan();
    ChuongTrinhUuDai ctudSelected = new ChuongTrinhUuDai();
    
    private void LoadData(){     
        
        tfMaPC.setText(pc.MAPC);
        tfMaKH.setText(pc.MAKH);
        ctpc = PhieuChupCon.LayCTPC(pc.MAPC);
        if (ctpc!=null){
            tfSoLuongAnh.setText(ctpc.SOANH);
        }
        tfNgayThanhToan.setText(DateCon.GetToDayString());
             
        LoadBHT();
        LoadCTHT();
        LoadCTUD();           
        TinhSoTien();
    }
    
    
    double soTien;
    float uuDai;
    long soAnh;
    long gia;
    private void TinhSoTien(){      
        cthtSelected = ctht.get(cbxCTHT.getSelectedIndex());
        ctudSelected = ctud.get(cbxCTUD.getSelectedIndex());
        try{          
            soAnh = Long.parseLong(tfSoLuongAnh.getText());
            gia = Long.parseLong(cthtSelected.GIA);
            uuDai = Float.parseFloat(ctudSelected.GIATRIUUDAI);
         }
        catch(NumberFormatException e){  
        }
        
        soTien =  (double)gia* (double)soAnh;
        soTien = soTien - (soTien/100)*uuDai;
        tfTongSoTien.setText(soTien+"");
    }
    
    private void LoadBHT(){
        bht= BangHoachToanCon.LayDanhSachBHT();
        ArrayList<String> strBHT = new ArrayList<>();
        if (bht!=null)
        for (int i=0; i< bht.size(); i++){
            strBHT.add(bht.get(i).TENBHT);
        }
        List<String> ls = new ArrayList<String>(strBHT); 
        cbxBHT.setModel(new DefaultComboBoxModel<String>(ls.toArray(new String[0])));
    }
    
    private void LoadCTHT(){
        int indexBHT = cbxBHT.getSelectedIndex();
        ctht= ChiTietHoachToanCon.LayDanhSachChiTietHoachToan(bht.get(indexBHT).MABHT);
        ArrayList<String> strCTHT = new ArrayList<>();
        if (ctht!=null)
        for (int i=0; i< ctht.size(); i++){
            strCTHT.add(ctht.get(i).NOIDUNG + ": " + ctht.get(i).GIA);
        }
        List<String> ls = new ArrayList<String>(strCTHT); 
        cbxCTHT.setModel(new DefaultComboBoxModel<String>(ls.toArray(new String[0])));

    }
    
    private void LoadCTUD(){
        ctud= ChuongTrinhUuDaiCon.LayDanhSachCTUDDangApDung();
        ArrayList<String> strCTUD = new ArrayList<>();
        if (ctud!=null)
        for (int i=0; i< ctud.size(); i++){
            strCTUD.add(ctud.get(i).TENCTUD +": "+ ctud.get(i).GIATRIUUDAI +" %");
        }
        List<String> ls = new ArrayList<String>(strCTUD); 
        cbxCTUD.setModel(new DefaultComboBoxModel<String>(ls.toArray(new String[0])));

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfMaPC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfMaKH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfSoLuongAnh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxBHT = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbxCTHT = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cbxCTUD = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        tfNgayThanhToan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfTongSoTien = new javax.swing.JTextField();
        btnThanhToan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Mã PC:");

        tfMaPC.setEditable(false);
        tfMaPC.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Mã KH:");

        tfMaKH.setEditable(false);
        tfMaKH.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("Số lượng ảnh:");

        tfSoLuongAnh.setEditable(false);
        tfSoLuongAnh.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setText("Bảng hoạch toán:");

        cbxBHT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxBHT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxBHTItemStateChanged(evt);
            }
        });

        jLabel5.setText("Chi tiết:");

        cbxCTHT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxCTHT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCTHTItemStateChanged(evt);
            }
        });

        jLabel6.setText("Chương trình ưu đãi:");

        cbxCTUD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxCTUD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCTUDItemStateChanged(evt);
            }
        });

        jLabel7.setText("Ngày thanh toán:");

        tfNgayThanhToan.setEditable(false);
        tfNgayThanhToan.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setText("Tổng số tiền:");

        tfTongSoTien.setEditable(false);
        tfTongSoTien.setBackground(new java.awt.Color(204, 204, 204));

        btnThanhToan.setText("Thanh toán");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThanhToan)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)
                        .addComponent(cbxCTHT, 0, 220, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(tfMaPC)
                        .addComponent(tfMaKH)
                        .addComponent(tfSoLuongAnh)
                        .addComponent(cbxBHT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxCTUD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfNgayThanhToan)
                        .addComponent(tfTongSoTien)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfMaPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfSoLuongAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxBHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxCTHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxCTUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNgayThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfTongSoTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxBHTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxBHTItemStateChanged
        // TODO add your handling code here:
        TinhSoTien();
    }//GEN-LAST:event_cbxBHTItemStateChanged

    private void cbxCTHTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCTHTItemStateChanged
        // TODO add your handling code here:
        TinhSoTien();
    }//GEN-LAST:event_cbxCTHTItemStateChanged

    private void cbxCTUDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCTUDItemStateChanged
        // TODO add your handling code here:
        TinhSoTien();
    }//GEN-LAST:event_cbxCTUDItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmThanhToanPhieuChup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmThanhToanPhieuChup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmThanhToanPhieuChup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmThanhToanPhieuChup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmThanhToanPhieuChup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JComboBox cbxBHT;
    private javax.swing.JComboBox cbxCTHT;
    private javax.swing.JComboBox cbxCTUD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tfMaKH;
    private javax.swing.JTextField tfMaPC;
    private javax.swing.JTextField tfNgayThanhToan;
    private javax.swing.JTextField tfSoLuongAnh;
    private javax.swing.JTextField tfTongSoTien;
    // End of variables declaration//GEN-END:variables
}
