
CREATE DATABASE IF NOT EXISTS QL_CHUPHINH CHARACTER SET 'UTF8' COLLATE 'UTF8_UNICODE_CI';

USE QL_CHUPHINH;


CREATE TABLE IF NOT EXISTS TAIKHOAN
(
 MANV VARCHAR(10) NOT NULL,
 TENNV VARCHAR(50) NOT NULL,
 MATKHAU VARCHAR(10) NOT NULL,
 LOAINV VARCHAR(50) NOT NULL
 );
 
 
 
 CREATE TABLE IF NOT EXISTS PHIEUCHUP
(
 MAPC VARCHAR(10) NOT NULL,
 MAKH VARCHAR(10) NOT NULL,
 NGAYTAO DATE,
 TRANGTHAI VARCHAR(20)
 );
 
 CREATE TABLE IF NOT EXISTS CHITIETPHIEUCHUP
(
 MACTPC VARCHAR(10) NOT NULL,
 MAPC VARCHAR(10) NOT NULL,
 ANH VARCHAR(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS KHACHHANG
(
 MAKH VARCHAR(11) NOT NULL,
 TENKH VARCHAR(50) NOT NULL,
 NGAYSINH DATE NOT NULL,
 SDT VARCHAR(20),
 EMAIL VARCHAR(20)
 );
 
 CREATE TABLE IF NOT EXISTS PHIEUTHANHTOAN
(
 MATT VARCHAR(10) NOT NULL,
 MAPC VARCHAR(10),
 MANV VARCHAR(10) NOT NULL,
 LOAI VARCHAR(50),
 NGAYTAO DATE,
 SOTIEN LONG
 );
 
 CREATE TABLE IF NOT EXISTS CHUONGTRINHUUDAI
 (
  MACTUD VARCHAR(10) NOT NULL,
  MANV VARCHAR(10) NOT NULL,
  TENCTUD VARCHAR(100) NOT NULL,
  NGAYBATDAU DATE,
  NGAYKETTHUC DATE,
  NOIDUNG VARCHAR(1000),
  GIATRIUUDAI FLOAT
 );
 
 CREATE TABLE IF NOT EXISTS BANGHOACHTOAN
 (
  MABHT VARCHAR(10) NOT NULL,
  MANV VARCHAR(10) NOT NULL,
  TENBHT VARCHAR(100) NOT NULL,
  NGAYTAO DATE,
  HIEULUC BOOLEAN
 );
 
 CREATE TABLE IF NOT EXISTS CHITIETHOACHTOAN
 (
  MACTHT VARCHAR(10) NOT NULL,
  MABHT VARCHAR(10) NOT NULL,
  NOIDUNG VARCHAR(1000),
  GIA LONG
 );
 
 CREATE TABLE IF NOT EXISTS BAOCAO
 (
  MABC VARCHAR(10) NOT NULL,
  MANV VARCHAR(10) NOT NULL,
  LOAIBC VARCHAR(100),
  TRANGTHAI VARCHAR(100),
  NOIDUNG VARCHAR(1000)
 );
 















