/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.DangNhapBUS;
import BUS.TaiKhoanBUS;
import DTO.TaiKhoan;
import DTO.ThongBao;
import java.awt.Color;
import java.awt.event.KeyEvent;
import DTO.DangNhap;

/**
 *
 * @author 16520
 */
public class frmDangNhap extends javax.swing.JFrame {

    /**
     * Creates new form frmDangNhap
     */
    public frmDangNhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbGNMK = new javax.swing.JCheckBox();
        cbTDDN = new javax.swing.JCheckBox();
        btnDangNhap = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfTaiKhoan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pfMatKhau = new javax.swing.JPasswordField();
        lbThongBao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        cbGNMK.setText("Ghi nhớ mật khẩu");

        cbTDDN.setText("Tự động đăng nhập");
        cbTDDN.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTDDNItemStateChanged(evt);
            }
        });

        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        jLabel1.setText("Tài khoản:");

        jLabel2.setText("Mật khẩu:");

        pfMatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfMatKhauKeyPressed(evt);
            }
        });

        lbThongBao.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbThongBao.setText("Thong bao");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbGNMK)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbThongBao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDangNhap))
                        .addComponent(tfTaiKhoan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                        .addComponent(pfMatKhau, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbTDDN, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbGNMK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTDDN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbThongBao)
                    .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
      
        DangNhap();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void DangNhap(){
        DangNhap dangNhap = new DangNhap(tfTaiKhoan.getText(), pfMatKhau.getText(), cbGNMK.isSelected(), cbTDDN.isSelected());
        
        ThongBao thongBao = TaiKhoanBUS.KiemTraDangNhap(tfTaiKhoan.getText(), pfMatKhau.getText());;
        if (thongBao.ThanhCong){
            quanlytiemchuphinh.QuanLyTiemChupHinh.taiKhoanDangNhap = TaiKhoanBUS.LayTaiKhoanTheoMa(tfTaiKhoan.getText());                    
            DangNhapBUS.LuuDangNhap(dangNhap);
            LoadDangNhap();       
        }      
        ShowThongBao(thongBao);
    }
    
    private void pfMatKhauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfMatKhauKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
           DangNhap();
        }
    }//GEN-LAST:event_pfMatKhauKeyPressed

    private void cbTDDNItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTDDNItemStateChanged
        // TODO add your handling code here:
        if (cbTDDN.isSelected()){
            cbGNMK.setSelected(true);
        }
    }//GEN-LAST:event_cbTDDNItemStateChanged

    public void Show(){
        this.setVisible(true);
        SERVICEFORM.Form.centreWindow(this);
        XoaThongBao();
        DangNhap dangNhap =DangNhapBUS.CheckDangNhap();
        if (dangNhap!=null){
            tfTaiKhoan.setText(dangNhap.TAIKHOAN);
            pfMatKhau.setText(dangNhap.MATKHAU);
            cbGNMK.setSelected(dangNhap.GHINHO);
            cbTDDN.setSelected(dangNhap.TUDONG);

            if (dangNhap.TUDONG){
                DangNhap();
            }
        }
    }
    
    public void ShowKhiDangXuat(){
        this.setVisible(true);
        SERVICEFORM.Form.centreWindow(this);
        XoaThongBao();
        DangNhap dangNhap =DangNhapBUS.CheckDangNhap();
        if (dangNhap!=null){         
            tfTaiKhoan.setText(dangNhap.TAIKHOAN);
            pfMatKhau.setText(dangNhap.MATKHAU);
            cbGNMK.setSelected(dangNhap.GHINHO);
            cbTDDN.setSelected(false);
            dangNhap.TUDONG= false;
        }
    }
    
    private void XoaThongBao(){
        lbThongBao.setText("");
    }
    
    private void ShowThongBao(ThongBao thongBao){
        lbThongBao.setText(thongBao.ChuThich);
        if (thongBao.ThanhCong){
           lbThongBao.setForeground(Color.GREEN);
        }
        else{
            lbThongBao.setForeground(Color.RED);
        }
    }
    private void LoadDangNhap(){
        frmHome home = new frmHome();
        switch (quanlytiemchuphinh.QuanLyTiemChupHinh.taiKhoanDangNhap.LOAINV){
            case "Ban lãnh đạo":            
                home.ShowBanLanhDao();
                break;
            case "Bộ phận giao dịch":
                home.ShowBoPhanGiaoDich();
                break;
            case "Bộ phận kế toán":
                home.ShowBoPhanKeToan();
                break;   
            case "Bộ phận tiếp thị":
               home.ShowBoPhanTiepThi();
               break;
            case "Bộ phận kỹ thuật":
                home.ShowBoPhanKyThuat();
                break;
            default:
                break;
        }
        this.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmDangNhap frmDN = new frmDangNhap();
                frmDN.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JCheckBox cbGNMK;
    private javax.swing.JCheckBox cbTDDN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbThongBao;
    private javax.swing.JPasswordField pfMatKhau;
    private javax.swing.JTextField tfTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
