/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.DateBUS;
import BUS.TaiKhoanBUS;
import DTO.TaiKhoan;
import DTO.ThongBao;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 16520
 */
public class frmQuanLyTaiKhoan extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmQuanLyTaiKhoan
     */
    public frmQuanLyTaiKhoan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnThemMoi = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfMaNV = new javax.swing.JTextField();
        tfTenNV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfMatKhau = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxBoPhan = new javax.swing.JComboBox();
        lbThongBao = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTaiKhoan = new javax.swing.JTable();
        tfTraCuuTenNV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxTraCuuBoPhan = new javax.swing.JComboBox();
        btnXoaTraCuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        btnThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES/iconfinder_Add_27831.png"))); // NOI18N
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES/iconfinder_Edit_27845.png"))); // NOI18N
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES/iconfinder_Delete_27842.png"))); // NOI18N
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã NV (tài khoản):");

        tfMaNV.setEditable(false);
        tfMaNV.setBackground(new java.awt.Color(204, 204, 204));

        tfTenNV.setEditable(false);
        tfTenNV.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Tên NV:");

        tfMatKhau.setEditable(false);
        tfMatKhau.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("Mật khẩu:");

        jLabel4.setText("Bộ phận");

        cbxBoPhan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bộ phận giao dịch", "Bộ phận tiếp thị", "Bộ phận kế toán", "Bộ phận kỹ thuật", "Ban lãnh đạo" }));

        lbThongBao.setText("Thông báo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThemMoi)
                        .addGap(40, 40, 40)
                        .addComponent(btnSua)
                        .addGap(35, 35, 35)
                        .addComponent(btnXoa))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbxBoPhan, javax.swing.GroupLayout.Alignment.LEADING, 0, 222, Short.MAX_VALUE)
                        .addComponent(tfMatKhau, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfTenNV, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbThongBao, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfMaNV, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxBoPhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lbThongBao)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTaiKhoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTaiKhoan);

        tfTraCuuTenNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTraCuuTenNVKeyReleased(evt);
            }
        });

        jLabel5.setText("Tên NV:");

        jLabel6.setText("Bộ phận");

        cbxTraCuuBoPhan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả", "Bộ phận giao dịch", "Bộ phận tiếp thị", "Bộ phận kế toán", "Bộ phận kỹ thuật", "Ban lãnh đạo" }));
        cbxTraCuuBoPhan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTraCuuBoPhanItemStateChanged(evt);
            }
        });

        btnXoaTraCuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES/iconfinder_Escape_Search_27877.png"))); // NOI18N
        btnXoaTraCuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTraCuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(tfTraCuuTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxTraCuuBoPhan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoaTraCuu)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxTraCuuBoPhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnXoaTraCuu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTraCuuTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void Show(){
        this.setVisible(true);
        XoaThongBao();
        LoadDanhSachTaiKhoan();
    }
    
    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        // TODO add your handling code here:
        frmTaoTaiKhoan frmTTK = new frmTaoTaiKhoan();
        frmTTK.Show();
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        TaiKhoan taiKhoan = new TaiKhoan(tfMaNV.getText(), tfTenNV.getText(),tfMatKhau.getText(), cbxBoPhan.getSelectedItem().toString() );
        ThongBao thongBao = TaiKhoanBUS.SuaTaiKhoan(taiKhoan);
        LoadDanhSachTaiKhoan();
        ShowThongBao(thongBao);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void XoaThongBao(){
        lbThongBao.setText("");
    }
    
    private void ShowThongBao(ThongBao thongBao){
        lbThongBao.setText(thongBao.ChuThich);
        if (thongBao.ThanhCong){
           lbThongBao.setForeground(Color.GREEN);
        }
        else{
            lbThongBao.setForeground(Color.RED);
        }
    }
    
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        TaiKhoan taiKhoan = new TaiKhoan(tfMaNV.getText(), tfTenNV.getText(),tfMatKhau.getText(), cbxBoPhan.getSelectedItem().toString() );
        ThongBao thongBao = TaiKhoanBUS.XoaTaiKhoan(taiKhoan);
        LoadDanhSachTaiKhoan();
        ShowThongBao(thongBao);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tableTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTaiKhoanMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tableTaiKhoan.getModel();

        // get the selected row index
       int selectedRowIndex = tableTaiKhoan.getSelectedRow();
       
        // set the selected row data into jtextfields
       tfMaNV.setText(model.getValueAt(selectedRowIndex, 0).toString());
       tfTenNV.setText(model.getValueAt(selectedRowIndex, 1).toString());
       tfMatKhau.setText(model.getValueAt(selectedRowIndex, 2).toString());
       cbxBoPhan.setSelectedItem(model.getValueAt(selectedRowIndex, 3).toString());
       
    }//GEN-LAST:event_tableTaiKhoanMouseClicked

    private void cbxTraCuuBoPhanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTraCuuBoPhanItemStateChanged
        // TODO add your handling code here:
        ArrayList<TaiKhoan> listTaiKhoan;
        if (cbxTraCuuBoPhan.getSelectedIndex() ==0){
            listTaiKhoan = TaiKhoanBUS.LayDanhSachTKTheoTen(tfTraCuuTenNV.getText());
        }
        else listTaiKhoan = TaiKhoanBUS.LayDanhSachTKTheoTenVaLoai(tfTraCuuTenNV.getText(),cbxTraCuuBoPhan.getSelectedItem().toString());
        ShowData(listTaiKhoan); 
    }//GEN-LAST:event_cbxTraCuuBoPhanItemStateChanged

    private void tfTraCuuTenNVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTraCuuTenNVKeyReleased
        // TODO add your handling code here:
        ArrayList<TaiKhoan> listTaiKhoan;
        if (tfTraCuuTenNV.getText().equals("")){
            LoadDanhSachTaiKhoan();
        }
        else{
            if (cbxTraCuuBoPhan.getSelectedIndex() ==0){
            listTaiKhoan = TaiKhoanBUS.LayDanhSachTKTheoTenVaLoai(tfTraCuuTenNV.getText(),"");
        }
        else listTaiKhoan = TaiKhoanBUS.LayDanhSachTKTheoTenVaLoai(tfTraCuuTenNV.getText(),cbxTraCuuBoPhan.getSelectedItem().toString());
        ShowData(listTaiKhoan); 
        }       
    }//GEN-LAST:event_tfTraCuuTenNVKeyReleased

    private void btnXoaTraCuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTraCuuActionPerformed
        // TODO add your handling code here:
        tfTraCuuTenNV.setText("");
        cbxTraCuuBoPhan.setSelectedIndex(0);
        LoadDanhSachTaiKhoan();
    }//GEN-LAST:event_btnXoaTraCuuActionPerformed

    private void LoadDanhSachTaiKhoan(){
        ArrayList<TaiKhoan> listTaiKhoan = TaiKhoanBUS.LayDanhSachTaiKhoan();
        ShowData(listTaiKhoan); 
    }
    
    private void ShowData(ArrayList<TaiKhoan> listTaiKhoan){
        tableTaiKhoan.clearSelection(); //Xoa du lieu table
        
        String header[] = {"Mã NV", "Tên NV", "Mật khẩu", "Bộ phận"};
        DefaultTableModel tblModel = new DefaultTableModel(header, 0);
        
        tblModel.setRowCount(0);
        
        if (listTaiKhoan != null) 
        {       
            // Trong khi chưa hết dữ liệu
           for (int i=0; i< listTaiKhoan.size(); i++){
                Vector data = new Vector();           
                data.add(listTaiKhoan.get(i).MANV);
                data.add(listTaiKhoan.get(i).TENNV);
                data.add(listTaiKhoan.get(i).MATKHAU);
                data.add(listTaiKhoan.get(i).LOAINV);
                // Thêm một dòng vào table model
                tblModel.addRow(data);
               }
        } 
        tableTaiKhoan.setModel(tblModel); // Thêm dữ liệu vào table   
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQuanLyTaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaTraCuu;
    private javax.swing.JComboBox cbxBoPhan;
    private javax.swing.JComboBox cbxTraCuuBoPhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbThongBao;
    private javax.swing.JTable tableTaiKhoan;
    private javax.swing.JTextField tfMaNV;
    private javax.swing.JTextField tfMatKhau;
    private javax.swing.JTextField tfTenNV;
    private javax.swing.JTextField tfTraCuuTenNV;
    // End of variables declaration//GEN-END:variables
}
