/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.KhachHangBUS;
import BUS.PhieuChupBUS;
import DTO.KhachHang;
import DTO.PhieuChup;
import DTO.ThongBao;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 16520
 */
public class frmThongTinKhachHang extends javax.swing.JFrame {

    /**
     * Creates new form frmThongTinKhachHang
     */
    public frmThongTinKhachHang() {
        initComponents();
    }

    public void Show(String MaKH){
        this.setVisible(true);
        SERVICEFORM.Form.centreWindow(this);
        XoaThongBao();
        ArrayList<PhieuChup> listPhieuChup = PhieuChupBUS.LayDanhSachPhieuChupTheoKhachHang(MaKH);
        ShowData(listPhieuChup);
        KhachHang kh = KhachHangBUS.LayKHTheoMa(MaKH);
        tfMaKH.setText(kh.MAKH);
        tfTenKH.setText(kh.TENKH);
        tfSDT.setText(kh.SDT);
        tfTongPC.setText(listPhieuChup.size() +"");
    }

    
    private void XoaThongBao(){
        lbThongBao.setText("");
    }
    
    private void ShowThongBao(ThongBao thongBao){
        lbThongBao.setText(thongBao.ChuThich);
        if (thongBao.ThanhCong){
           lbThongBao.setForeground(Color.GREEN);
        }
        else{
            lbThongBao.setForeground(Color.RED);
        }
    }
    
    private void ShowData(ArrayList<PhieuChup> listPhieuChup){
        
        tablePhieuChup.clearSelection(); //Xoa du lieu table
        
        String header[] = {"Mã PC", "Mã KH", "Ngày tạo", "Trạng thái"};
        DefaultTableModel tblModel = new DefaultTableModel(header, 0);
        
        tblModel.setRowCount(0);
        
        if (listPhieuChup != null) 
        {       
            // Trong khi chưa hết dữ liệu
           for (int i=0; i< listPhieuChup.size(); i++){
                Vector data = new Vector();           
                data.add(listPhieuChup.get(i).MAPC);
                data.add(listPhieuChup.get(i).MAKH);
                data.add(listPhieuChup.get(i).NGAYTAO);
                data.add(listPhieuChup.get(i).TRANGTHAI);
                // Thêm một dòng vào table model
                tblModel.addRow(data);
               }
        } 
        tablePhieuChup.setModel(tblModel); // Thêm dữ liệu vào table  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfMaKH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfTenKH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfTongPC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfPCDangChon = new javax.swing.JTextField();
        lbThongBao = new javax.swing.JLabel();
        btnThemPC = new javax.swing.JButton();
        btnCapNhatPC = new javax.swing.JButton();
        tfSDT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePhieuChup = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Mã KH:");

        tfMaKH.setEditable(false);
        tfMaKH.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Tên KH:");

        tfTenKH.setEditable(false);
        tfTenKH.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("Tổng số PC:");

        tfTongPC.setEditable(false);
        tfTongPC.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setText("Mã PC đang chọn:");

        tfPCDangChon.setEditable(false);
        tfPCDangChon.setBackground(new java.awt.Color(204, 204, 204));

        btnThemPC.setText("Thêm PC");
        btnThemPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPCActionPerformed(evt);
            }
        });

        btnCapNhatPC.setText("Cập nhật PC");
        btnCapNhatPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatPCActionPerformed(evt);
            }
        });

        tfSDT.setEditable(false);
        tfSDT.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setText("SDT:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbThongBao)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnThemPC)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnCapNhatPC, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                        .addComponent(jLabel1)
                        .addComponent(tfMaKH)
                        .addComponent(jLabel2)
                        .addComponent(tfTenKH)
                        .addComponent(jLabel3)
                        .addComponent(tfTongPC)
                        .addComponent(jLabel4)
                        .addComponent(tfPCDangChon)
                        .addComponent(tfSDT))
                    .addComponent(jLabel5))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tfTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(tfTongPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(tfPCDangChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(lbThongBao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemPC, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnCapNhatPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        tablePhieuChup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePhieuChup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePhieuChupMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePhieuChup);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablePhieuChupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePhieuChupMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)tablePhieuChup.getModel();

        // get the selected row index
       int selectedRowIndex = tablePhieuChup.getSelectedRow();
       
        // set the selected row data into jtextfields
       tfPCDangChon.setText(model.getValueAt(selectedRowIndex, 0).toString());
    }//GEN-LAST:event_tablePhieuChupMouseClicked

    private void btnCapNhatPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatPCActionPerformed
        // TODO add your handling code here:
        if (tfPCDangChon.getText()!=""){
            PhieuChup pc = PhieuChupBUS.LayPhieuChupTheoMa(tfPCDangChon.getText());
            frmCapNhatPhieuChup frmCNPC = new frmCapNhatPhieuChup();      
            frmCNPC.Show(pc, null, false);
            this.setVisible(false);
        }
       
    }//GEN-LAST:event_btnCapNhatPCActionPerformed

    private void btnThemPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPCActionPerformed
        // TODO add your handling code here:
        frmThemPhieuChup frmTPC = new frmThemPhieuChup();
        frmTPC.Show(KhachHangBUS.LayKHTheoMa(tfMaKH.getText()));
        this.setVisible(false);
    }//GEN-LAST:event_btnThemPCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmThongTinKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmThongTinKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmThongTinKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmThongTinKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmThongTinKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatPC;
    private javax.swing.JButton btnThemPC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbThongBao;
    private javax.swing.JTable tablePhieuChup;
    private javax.swing.JTextField tfMaKH;
    private javax.swing.JTextField tfPCDangChon;
    private javax.swing.JTextField tfSDT;
    private javax.swing.JTextField tfTenKH;
    private javax.swing.JTextField tfTongPC;
    // End of variables declaration//GEN-END:variables
}
